spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3307/calculator?serverTimezone=UTC
    username: root
    password: azerty

  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    #disable liquibase at start-up
    enabled: false


server:
  port: 9003